apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-backend
spec:
    replicas: 2
    selector:
      matchLabels:
        app: rent-backend
    template:
      # 这里是 Pod 模板
      metadata:
        labels:
          app: rent-backend
      spec:
        volumes:
          - name: config-volume
            configMap:
              name: devconf
#              items:
#                - key: dev.env
#                  path: app/conf/dev.env
        containers:
          - name: rent-backend
            image: go_rent
            resources:
#            lifecycle:
#              postStart:
#                exec:
            # 可能会报错，因为在挂载dev.env前执行了
            entrypoint: ["/app/server"]
            imagePullPolicy: Never
            ports:
              - containerPort: 8000
                protocol: TCP
            volumeMounts:
              - mountPath: /app/conf/dev.env # 无configMap.items，结果：app.conf  dev.env mytest
                name: config-volume
                subPath: dev.env

#              volumeMounts:
#                - name: test-path
#                  mountPath: /a/b/c
#                  subPath: d   在c目录中你有一些文件1.txt，2.txt然后子路径将重写这些内容c并创建新目录d