apiVersion: v1
kind: Service
metadata:
  name: go-rent-service
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8000
      nodePort: 31000
  type: LoadBalancer
  selector:
    app: rent-backend
